//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKEO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresse
    {
        public long id { get; set; }
        public decimal codepostal { get; set; }
        public string adresse1 { get; set; }
        public int id_utilisateur { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
