//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKEO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleCommande
    {
        public int id { get; set; }
        public int id_commande { get; set; }
        public int id_article { get; set; }
        public int quantite { get; set; }
        public Nullable<double> prix { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Commande Commande { get; set; }
    }
}
