//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKEO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Couleur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Couleur()
        {
            this.ArticleCouleurs = new HashSet<ArticleCouleurs>();
        }
    
        public int id { get; set; }
        public string couleur1 { get; set; }
        public string hexadecimal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleCouleurs> ArticleCouleurs { get; set; }
    }
}
