//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKEO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IkeoDBEntities : DbContext
    {
        public IkeoDBEntities()
            : base("name=IkeoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresse> Adresse { get; set; }
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<ArticleCommande> ArticleCommande { get; set; }
        public virtual DbSet<ArticleCouleurs> ArticleCouleurs { get; set; }
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<Commande> Commande { get; set; }
        public virtual DbSet<Couleur> Couleur { get; set; }
        public virtual DbSet<Notation> Notation { get; set; }
        public virtual DbSet<Panier> Panier { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
        public virtual DbSet<ImagesArticle> ImagesArticle { get; set; }
        public virtual DbSet<ArticlePanier> ArticlePanier { get; set; }
        public virtual DbSet<CarteBancaire> CarteBancaire { get; set; }
    }
}
