//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKEO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilisateur()
        {
            this.Adresse = new HashSet<Adresse>();
            this.Notation = new HashSet<Notation>();
        }
    
        public string email { get; set; }
        public string mdp { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public bool confirm { get; set; }
        public long id_panier { get; set; }
        public Nullable<int> id_cartebancaire { get; set; }
        public int id_role { get; set; }
        public int id { get; set; }
        public string civilite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adresse> Adresse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notation> Notation { get; set; }
        public virtual Panier Panier { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual CarteBancaire CarteBancaire { get; set; }
    }
}
